server:
  context-path: /seller
  port: 8082

rpc.manager.url: http://localhost:8081/manager/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/financial_seller?user=root&password=root&useUnicode=true&characterEncoding=utf-8

logging:
  level:
    com.googlecode.jsonrpc4j: debug
